title: "My Personal Library"
description: "A dark academia personal library of my books"
baseurl: "" 
url: "https://yourusername.github.io"

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-tagging

paginate: 10
paginate_path: "/page:num/"

author:
  name: Your Name

collections:
  books:
    output: true
    permalink: /books/:title/

defaults:
  - scope:
      path: ""
      type: books
    values:
      layout: single
